---
title: "Ben Litterer Personal Site"
---

## My Projects ##

Although I am generally very slow to keep my github updated, here is a summary of the various projects I have been or currently am involved in... 

# Protein Functional Annotations #
Given the incredibly large amount of sequences, there is a great opportunity to leverage this data to find more interesting aspects of proteins such as their function. Recently, high performing methods have featured machine learning algorithms such as k nearest neighbors classification or even neural networks. All of the high performing methods are still highly dependant on sequence alignment tools, meaning that there is a bottleneck in this area. A labmate of mine and member of Jernigan lab, Kejue Jia, has created a sequence alignment tool that takes structural information into account when finding sequence matches. I have applied this new methodology to annotate proteins with functions that are much more specific than those found with convential methods. This method finds many protein functions that have only previously been found through experimental methods, which are much more costly and slow. 

Portions of this work can be found in a publication by the American Chemical Society and on my personal github account. 

ACS publication: https://pubs.acs.org/doi/abs/10.1021/bk-2020-1356.ch006

github: https://github.com/blitt2018 